version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
        interval: "weekly"
        day: "monday"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "upd"
      prefix-development: "Updated version:"
      include: "scope"
