name: Build
on:
 push:
  branches:
   - main
jobs:
 build:
  runs-on: self-hosted
  steps:
   - name: Set up QEMU
     uses: docker/setup-qemu-action@v2.2.0-uses
   - name: Set up Docker Buildx
     uses: docker/setup-buildx-action@v2.5.0
   - name: Build and push
     uses: docker/build-push-action@v4.1.1
     with:
      file: Dockerfile
      push: true
      tags: user/app:latest
