name: Check
on: push
jobs:
 lint:
   build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [15]
  steps:
   - name: Checkout
     uses: actions/checkout@v3
   - uses: pnpm/action-setup@v3
     with:
      version: 8
   - name: Install deps
     run: pnpm install
   - name: Lint
     run: pnpm run lint
